{{ if not .Values.data.deploy.standalone }}
{{ with .Values.redis }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret_name }}
  labels:
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
stringData:
  password: {{ .password | quote }}
{{ end }}
{{- end }}